export const ATTRIBUTE_STATES = {
  0: { label: 'False', next: 1 },
  1: { label: 'True', next: 2 },
  2: { label: 'Unknown', next: 0 },
};

export const ATTRIBUTE_COLORS = {
  black: '#111827',
  blue: '#2563eb',
  brown: '#8b5e34',
  green: '#16a34a',
  grey: '#6b7280',
  orange: '#f97316',
  pink: '#ec4899',
  purple: '#9333ea',
  red: '#dc2626',
  white: '#ffffff',
  yellow: '#eab308',
};

export const DEFAULT_ATTRIBUTES = [
  'Age-Young',
  'Age-Adult',
  'Age-Old',
  'Gender-Female',
  'Gender-Male',
  'UpperBody-Color-Black',
  'UpperBody-Color-Blue',
  'UpperBody-Color-Brown',
  'UpperBody-Color-Green',
  'UpperBody-Color-Grey',
  'UpperBody-Color-Orange',
  'UpperBody-Color-Pink',
  'UpperBody-Color-Purple',
  'UpperBody-Color-Red',
  'UpperBody-Color-White',
  'UpperBody-Color-Yellow',
  'LowerBody-Color-Black',
  'LowerBody-Color-Blue',
  'LowerBody-Color-Brown',
  'LowerBody-Color-Green',
  'LowerBody-Color-Grey',
  'LowerBody-Color-Orange',
  'LowerBody-Color-Pink',
  'LowerBody-Color-Purple',
  'LowerBody-Color-Red',
  'LowerBody-Color-White',
  'LowerBody-Color-Yellow',
  'Accessory-Backpack',
  'Accessory-Bag',
  'Accessory-Hat',
];
